
-- Select the funding database
USE funding;

-- Disable foreign key checks temporarily
SET foreign_key_checks = 0;

-- Begin the transaction
START TRANSACTION;

-- Drop the table if it exists
DROP TABLE IF EXISTS nserc_awards;

-- Create the nserc_awards table with proper data types
CREATE TABLE nserc_awards (
    id INT PRIMARY KEY,
    compt_year INT,
    fisc_year VARCHAR(20),
    prj_lead_firstname VARCHAR(255),
    prj_lead_lastname VARCHAR(255),
    inst VARCHAR(255),
    dept VARCHAR(255),
    prvnc VARCHAR(100),
    award_amount VARCHAR(100),
    instlmnt VARCHAR(50),
    prgrm VARCHAR(255),
    sel_comt VARCHAR(255),
    resrch_subj VARCHAR(255),
    area VARCHAR(255),
    co_resrch VARCHAR(255),
    co_partnr VARCHAR(255),
    award_summary TEXT
);
ALTER DATABASE funding CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE nserc_awards CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SET SESSION sql_mode = '';

-- Insert data into the nserc_awards table
INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('600000', '2015', '2016-2017', 'Martin', 'Béland', 'Université Laval', 'Sciences géomatiques', 'Québec', '$42,000', '2 - 3', 'Collaborative Research and Development Grants', 'RPP Internal Decision Cttee', 'Remote sensing', 'Environmental impact of economic activities (including agriculture)', 'No Co-Researcher', 'Map Track Solutions Inc.', 'La compagnie Geotracability offre un service web permettant à ses clients de suivre la distribution géographique des producteurs d''huile de palme auprès desquels ils s''approvisionnent pour la production d''aliments, de cosmétiques et de biocarburants. Les données cartographiques utilisées sont suffisantes pour répondre au besoin des clients d''assurer la durabilité de leur chaine d''approvisionnement. Mais ceux-ci doivent également répondre aux critiques grandissantes envers les activités de production d''huile de palme qui sont à l''origine d''une déforestation incontrôlée dans plusieurs pays d''Afrique et d''Asie. Certaines compagnies clientes de Geotracability ont pris des engagements afin de réduire ou d''éliminer la déforestation dans la chaîne de production de leurs produits, mais les moyens actuellement mis en oeuvre suscitent des doutes quant à leur efficacité. C''est pourquoi Geotracability souhaite bonifier son offre de service en ajoutant une fonctionnalité de surveillance de la déforestation, basée sur la télédétection satellitaire. La nouvelle plateforme Google Earth Engine a été choisie comme environnement de développement pour générer des alertes de déforestation qui seront mises au service des clients de Geotracability. Google Earth Engine offre une vaste couverture spatiale et temporelle grâce à son entrepôt contenant 3.6 million d''images acquises par les satellites Landsat 4, 5, 6, 7 et 8, une grande puissance de traitement grâce à une infrastructure d''informatique en nuage, ainsi qu''une grande flexibilité grâce à un environnement de programmation (API) qui permet aux développeurs d''effectuer des analyses poussées et personnalisées. Une approche de gestion de l''incertitude sera développée et appliquée afin de minimiser les coûts liés aux fausses alertes pour les clients de Geotracability. L''expertise développée avec la nouvelle technologie Google Earth Engine pourra être mise au service d''autres applications de surveillance et de gestion durable des ressources forestières canadiennes et mondiales. De plus, la stratégie de gestion du risque lié à l''incertitude pourra être exploitée par l''ensemble des producteurs et diffuseurs canadiens de données géospatiales qui se retrouvent dans un contexte de type experts au service de non-experts.');
INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('600001', '2015', '2016-2017', 'Liuchen', 'Chang', 'University of New Brunswick', 'Electrical and Computer Engineering', 'New Brunswick', '$240,000', '2 - 5', 'Collaborative Research and Development Grants', 'University/Industry', 'Energy conversion and distribution', 'Electrical energy', 'Castillo Guerra, EduardoDiduch, Chris', 'Siemens Canada Limited', 'Power systems need new resources to provide ancillary services and to serve peak load in order to integrate variable renewable energy generation and to meet the steadily growing electricity demand. Traditionally these additional power system resources have been provided by central generation plants. However, environmental concerns and capital expenditure constraints often impose limitations to adding new large generation facilities. The research team at UNB has proposed an alternative and innovative concept of aggregated direct load control for ancillary services, which will have a profound influence to the operation of power system resources under the smart grid environment.  The objectives of this CRD project are to develop innovative technologies of direct load control for creating alternative power system resources without negative impact to customers'' end use, and to transfer advanced technologies to Canadian industry for commercialization. These R&D endeavours will contribute to a long term goal of transforming the operation of power systems from generation following consumption to partial consumption following optimized generation, thus improving the overall efficient operation of power systems and integrating more renewable power generation. This CRD project was developed jointly by the research team and Siemens Canada. The project focuses on developing models, forecasting methods, and control strategies of aggregated loads for peak load reduction and ancillary services, and on investigating the impact of direct load control on power distribution networks. The developed technologies will be integrated into Siemens'' Decentralized Energy Management System (DEMS) and Siemens'' Demand Response Management System (DRMS) platforms. This project will provide joint training by university researchers and industry experts for 16 Ph.D. and M.Sc. students, and 5 post-doctoral fellows, providing industry and universities with highly qualified personnel with advanced knowledge, hands-on experience and engineering skills.');
INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('600002', '2015', '2016-2017', 'JeanPascal', 'LepetitStoffaes', 'Université Laval', 'Génie chimique', 'Québec', '$9,000', 'Not available', 'Industrial Scholarship in Partnership with the FQRNT- Doctoral', 'Scholarships & Fellowships', 'Molecular biology', 'Not available', 'No Co-Researcher', 'No Partners', 'No summary - Aucun sommaire');
INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('600003', '2015', '2016-2017', 'Vanessa', 'Simard', 'Université Laval', 'Génie mécanique', 'Québec', '$7,000', 'Not available', 'Industrial Scholarship in Partnership with the FQRNT - Master''s', 'Scholarships & Fellowships', 'Industrial engineering', 'Not available', 'No Co-Researcher', 'No Partners', 'No summary - Aucun sommaire');



INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('449320', '2007', '2010-2011', 'Philippe', 'Viarouge', 'Université Laval', 'Génie électrique et génie informatique', 'Québec', '$37,910', '4 - 5', 'Discovery Grants Program - Individual', 'Electromag. & Electr. Systems (H)', 'Energy conversion and distribution', 'Electrical energy', 'No Co-Researcher', 'No Partners', 'Le projet consiste à développer des outils méthodologiques nécessaires pour favoriser la diffusion d''une nouvelle technologie de fabrication des machines électriques basée sur l''utilisation des matériaux magnétiques composites. Les «Soft Magnetic Composites» ou SMC sont des matériaux magnétiques composites doux, dans lesquels les particules de Fer sont séparées par un diélectrique de très faible épaisseur. Cette isolation réduit l''apparition des pertes par courants induits en courant alternatif. La présence d''un entrefer distribué tridimensionnel confère à ces matériaux une isotropie de leurs propriétés magnétiques et thermiques, qui permet de concevoir des machines électriques dans lesquelles le flux magnétique peut circuler en 3 dimensions. La technologie SMC permet de réduire le coût de production des machines électriques en utilisant les procédés de la métallurgie des poudres : production du circuit magnétique par pressage direct sans pertes de matériel, minimisation des étapes d''assemblage, recyclage aisé des pièces en fin de vie. L''objectif principal du projet consiste  à privilégier une approche de conception intégrée entre les trois intervenants de la chaîne de conception et de production : les concepteurs et les manufacturiers de matériaux SMC, les concepteurs et les manufacturiers de pièces en SMC, les concepteurs de machines électriques utilisant les SMC. La recherche s''articule autour de trois thèmes complémentaires permettant de développer des passerelles méthodologiques entre ces trois types de concepteurs: la modélisation et la caractérisation des SMC, la recherche topologique et la méthodologie de CAO des machines électriques utilisant les SMC.');
INSERT INTO nserc_awards (id, compt_year, fisc_year, prj_lead_firstname, prj_lead_lastname, inst, dept, prvnc, award_amount, instlmnt, prgrm, sel_comt, resrch_subj, area, co_resrch, co_partnr, award_summary) VALUES ('449321', '2009', '2010-2011', 'Rabab', 'Ward', 'University of British Columbia', 'Electrical and Computer Engineering', 'British Columbia', '$46,000', '2 - 5', 'Discovery Grants Program - Individual', 'Electrical and Computer Engineering', 'Digital signal processing', 'Biomedical engineering', 'No Co-Researcher', 'No Partners', 'This proposal focuses on the applications of digital signal processing and machine learning to the brain computer interface (BCI) and face recognition areas. A BCI allows a user to control a device such as a wheelchair or a computer by thinking of it only. The user''s brain signals are automatically processed to detect the presence (if any) of the user''s intention to control. Our research focuses on designing achieve a high-performance and reliable self-paced BCI (SBCI) system. An SBCI allows users to affect control at any time they wish and not only at specific times specified by the system (unlike the traditional BCI systems). Our main goals are to improve the performance of present SBCI''s, obtain robust performance in the presence of artifacts, and increase the information transfer rate by adding more control options. Face recognition is a biometric method that involves identifying a person in a stored database of faces, given an image of a face to be recognized. Much progress has been achieved in this field. However, building a practical automated face recognition system that deals with the scarcity of training data and works under varying imaging conditions (such as different face poses, different illumination conditions, different facial expressions, and occlusions) remains a very challenging problem. To address these problems, we plan to develop new and improved feature extraction methods and design superior classification algorithms that result in an automated face recognition system with a high performance.');
-- Commit the transaction
COMMIT;

-- Re-enable foreign key checks
SET foreign_key_checks = 1;